<a href="https://colab.research.google.com/github/Yalda-Ashrafi/TensorFlow/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
mnist=tf.keras.datasets.mnist

(x_train,y_train), (x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255,x_test/255

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                  tf.keras.layers.Dense(128,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10)])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.10533981, -0.05160812,  0.22777471, -0.04279661,  0.39559013,
        -0.47781643, -1.1723088 ,  0.39731988, -0.01099466, -0.23850228]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.11161724, 0.09540467, 0.12615488, 0.09624904, 0.14920568,
        0.06229737, 0.03110681, 0.149464  , 0.09935915, 0.07914118]],
      dtype=float32)

In [7]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.775836)

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9123 - loss: 0.3011
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9581 - loss: 0.1441
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9668 - loss: 0.1078
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.9719 - loss: 0.0903
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9769 - loss: 0.0745


In [9]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 2s - 5ms/step - accuracy: 0.9736 - loss: 0.0809


[0.08088730275630951, 0.9735999703407288]

In [12]:
Probability_model=tf.keras.Sequential([model,tf.keras.layers.Softmax()])
Probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.5151599e-08, 1.0886005e-09, 9.6562064e-07, 1.4360550e-04,
        2.6122014e-11, 1.5777033e-08, 1.5076716e-14, 9.9977642e-01,
        4.1037777e-07, 7.8578487e-05],
       [3.3552001e-09, 1.0358678e-05, 9.9972731e-01, 1.5188528e-04,
        1.3634607e-15, 6.3830720e-07, 3.0786186e-08, 9.7311489e-14,
        1.0975050e-04, 1.5598932e-13],
       [4.2821651e-07, 9.9875176e-01, 3.2186889e-04, 3.7424031e-06,
        1.6822156e-05, 6.0582288e-06, 9.6652466e-06, 6.2872423e-04,
        2.6042730e-04, 5.1793154e-07]], dtype=float32)>